version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_USER: desafiodock
      POSTGRES_PASSWORD: desafiodock
      POSTGRES_DB: postgres
    ports:
      - 5432:5432
